apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "deel-task-helm.fullname" . }}
  labels:
    {{- include "deel-task-helm.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "deel-task-helm.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "deel-task-helm.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 8008
              protocol: TCP
          env:
            - name: POSTGRES_USER
              value: {{ .Values.env.POSTGRES_USER }}
            - name: POSTGRES_PASSWORD
              value: {{ .Values.env.POSTGRES_PASSWORD }}
            - name: POSTGRES_DB
              value: {{ .Values.env.POSTGRES_DB }}
            - name: POSTGRES_HOST
              value: {{ .Values.env.POSTGRES_HOST }}
            - name: DATABASE_URL
              value: {{ .Values.env.DATABASE_URL }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}