apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "deel-task-helm.fullname" . }}
  annotations:
    kubernetes.io/ingress.class: nginx
spec:
  rules:
  - host: deel-task.plsg.io
    http:
      paths:
      - pathType: Prefix
        path: "/reverse"
        backend:
          service:
            name: {{ include "deel-task-helm.fullname" . }}
            port:
              number: {{ .Values.service.port }}