apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "deel-task-helm.fullname" . }}
  annotations:
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/ssl-redirect: True
    # You can add other AWS ALB specific annotations here as required.
spec:
  ingressClassName: alb
  rules:
    - http:
        paths:
          - path: /reverse
            pathType: Prefix
            backend:
              service:
                name: {{ include "deel-task-helm.fullname" . }}
                port:
                  number: {{ .Values.service.port }}
