replicaCount: 1

image:
  repository: ayobuba/deel-task_web
  pullPolicy: IfNotPresent
  tag: "latest"

service:
  type: NodePort
  port: 5000

resources: {}

env:
  POSTGRES_USER: ""
  POSTGRES_PASSWORD: ""
  POSTGRES_DB: "ips"
  POSTGRES_HOST: ""
  DATABASE_URL: ""