replicaCount: 1

image:
  repository: ayobuba/deel-task_web
  pullPolicy: IfNotPresent
  tag: "latest"

service:
  type: ClusterIP
  port: 8008

resources: {}

env:
  - name: POSTGRES_USER
    value: deeluser
  - name: POSTGRES_PASSWORD
    value: geostore123
  - name: POSTGRES_DB
    value: ips
  - name: POSTGRES_HOST
    value: reverse-ip-2.c3rq3bzfdudl.eu-central-1.rds.amazonaws.com
  - name: DATABASE_URL
    value: postgresql://deeluser:geostore123@reverse-ip-2.c3rq3bzfdudl.eu-central-1.rds.amazonaws.com:5432/ips